apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-c
spec:
  selector:
    matchLabels:
      app: myapp-c
  template:
    metadata:
      labels:
        app: myapp-c
    spec:
      containers:
      - name: myapp-c
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80 # Port exposed by the container
